#!/usr/bin/env bash
set -e

# Only on staging
[[ "$KAMAL_DESTINATION" == "staging" ]] || exit 0

# Run migrations inside the primary, running web container
kamal app exec \
  -d staging \
  -p \
  -- rails db:prepare