service: prime_villa
image: samadesoga/prime_villa
servers:
  web:
    hosts:
      - 195.201.147.221
registry:
  username: samadesoga
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
builder:
  arch:
      - amd64
      - arm64
aliases:
  shell: app exec -i --reuse "bash"
  console: app exec -i --reuse "bin/rails console"
  rake: app exec -i --reuse "bundle exec rake"
