# Override service name so containers don’t collide
service: prime_villa-staging
# Tag your staging image
image: samadesoga/prime_villa

env:
  clear:
    RAILS_ENV: "staging"
    ROOT_URL: http://staging.theprimevilla.com/
    PORT: "5000"
volumes:
  - "/db/staging.sqlite3:/rails/db/staging.sqlite3"
  - "/storage:/rails/storage"

proxy:
  ssl: true
  host: staging.theprimevilla.com
  app_port: 5000