service: prime_villa
image: samadesoga/prime_villa
servers:
  web:
    hosts:
      - root@195.201.147.221
registry:
  username: samadesoga
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
builder:
  multiarch: false
# no proxy here—each env will set its own host
