service: prime_villa
image: samadesoga/prime_villa
servers:
  web:
    hosts:
      - 195.201.147.221
registry:
  username: samadesoga
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch:
      - amd64
      - arm64
# no proxy here—each env will set its own host
hooks:
  pre_deploy:
    - name: "Run DB migrations"
      run: |
        # only run on the primary web role
        VERSION=$KAMAL_VERSION kamal app exec -p "./bin/rails db:prepare"
