# This is the actual configuration file for litestream.
#
# You can either use the generated `config/initializers/litestream.rb`
# file to configure the litestream-ruby gem, which will populate these
# ENV variables when using the `rails litestream:replicate` command.
#
# Or, if you prefer, manually manage ENV variables and this configuration file.
# In that case, simply ensure that the ENV variables are set before running the
# `replicate` command.
#
# For more details, see: https://litestream.io/reference/config/
dbs:
  - path: storage/staging.sqlite3
    replicas:
      - type: s3
        bucket: crm-prime-villa 
        path: storage/staging.sqlite3
        access-key-id: AKIAYF4JFVMXG2RQQHQ2
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
        sync-interval: 240h
  - path: storage/staging_queue.sqlite3
    replicas:
      - type: s3
        bucket: crm-prime-villa
        path: storage/staging_queue.sqlite3
        access-key-id: AKIAYF4JFVMXG2RQQHQ2
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
        sync-interval: 240h
  - path: storage/production.sqlite3
    replicas:
      - type: s3
        bucket: crm-prime-villa
        path: storage/production.sqlite3
        access-key-id: AKIAYF4JFVMXG2RQQHQ2
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
        sync-interval: 240h
  - path: storage/production_queue.sqlite3
    replicas:
      - type: s3
        bucket: crm-prime-villa
        path: storage/production_queue.sqlite3
        access-key-id: AKIAYF4JFVMXG2RQQHQ2
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
        sync-interval: 240h
